#!/bin/bash

if [ -f /etc/default/cmis ]; then
    . /etc/default/cmis
fi

JAR="$EXTRA_CLASSPATH:/etc/cmis/:/usr/share/cmis/cmis.jar"
CONFIG="/etc/cmis/cmis.config"
COMMAND="start"
AGGRESSIVE_OPTS="-XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSParallelRemarkEnabled -XX:+AggressiveOpts -XX:+UseFastAccessorMethods -XX:+UseCompressedOops -XX:+CMSClassUnloadingEnabled"

usage()
{
  cat << EOF
usage: $0 [-a] [java options ...] [command] [config-file]

Runs CMIS with the given configuration file.

OPTIONS:
  -h    Show this message
  -a    Adds some default aggressive, nonportable JVM optimization flags.

COMMANDS:
  start    Start the CMIS server (this is the default)
  test     Run the configuration tests

  Any unrecognized options (e.g. -XX:+UseParNewGC) will be passed on to java.
EOF
}

OPTS=
for arg in "$@"; do
  case $arg in
    "-a")
      OPTS="$AGGRESSIVE_OPTS $OPTS"
      ;;
    "-h")
      usage
      exit 0
      ;;
    -*)
      OPTS="$OPTS $arg"
      ;;
    test|start)
      COMMAND="$arg"
      ;;
    *)
      CONFIG="$arg"
     ;;
  esac
done

exec java $EXTRA_JAVA_OPTS $OPTS -cp "$JAR" cmis.bin "$CONFIG"
