
package vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-17T16:08:07.776+02:00
 * Generated source version: 2.7.5
 */

@WebFault(name = "ActiveDirectoryFaultFault", targetNamespace = "urn:vim25")
public class ActiveDirectoryFaultFaultMsg extends Exception {
    
    private vmware.vim25.ActiveDirectoryFault activeDirectoryFaultFault;

    public ActiveDirectoryFaultFaultMsg() {
        super();
    }
    
    public ActiveDirectoryFaultFaultMsg(String message) {
        super(message);
    }
    
    public ActiveDirectoryFaultFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public ActiveDirectoryFaultFaultMsg(String message, vmware.vim25.ActiveDirectoryFault activeDirectoryFaultFault) {
        super(message);
        this.activeDirectoryFaultFault = activeDirectoryFaultFault;
    }

    public ActiveDirectoryFaultFaultMsg(String message, vmware.vim25.ActiveDirectoryFault activeDirectoryFaultFault, Throwable cause) {
        super(message, cause);
        this.activeDirectoryFaultFault = activeDirectoryFaultFault;
    }

    public vmware.vim25.ActiveDirectoryFault getFaultInfo() {
        return this.activeDirectoryFaultFault;
    }
}
