
package vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-17T16:08:07.387+02:00
 * Generated source version: 2.7.5
 */

@WebFault(name = "AlreadyExistsFault", targetNamespace = "urn:vim25")
public class AlreadyExistsFaultMsg extends Exception {
    
    private vmware.vim25.AlreadyExists alreadyExistsFault;

    public AlreadyExistsFaultMsg() {
        super();
    }
    
    public AlreadyExistsFaultMsg(String message) {
        super(message);
    }
    
    public AlreadyExistsFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public AlreadyExistsFaultMsg(String message, vmware.vim25.AlreadyExists alreadyExistsFault) {
        super(message);
        this.alreadyExistsFault = alreadyExistsFault;
    }

    public AlreadyExistsFaultMsg(String message, vmware.vim25.AlreadyExists alreadyExistsFault, Throwable cause) {
        super(message, cause);
        this.alreadyExistsFault = alreadyExistsFault;
    }

    public vmware.vim25.AlreadyExists getFaultInfo() {
        return this.alreadyExistsFault;
    }
}
