
package vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-17T16:08:07.845+02:00
 * Generated source version: 2.7.5
 */

@WebFault(name = "AlreadyUpgradedFault", targetNamespace = "urn:vim25")
public class AlreadyUpgradedFaultMsg extends Exception {
    
    private vmware.vim25.AlreadyUpgraded alreadyUpgradedFault;

    public AlreadyUpgradedFaultMsg() {
        super();
    }
    
    public AlreadyUpgradedFaultMsg(String message) {
        super(message);
    }
    
    public AlreadyUpgradedFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public AlreadyUpgradedFaultMsg(String message, vmware.vim25.AlreadyUpgraded alreadyUpgradedFault) {
        super(message);
        this.alreadyUpgradedFault = alreadyUpgradedFault;
    }

    public AlreadyUpgradedFaultMsg(String message, vmware.vim25.AlreadyUpgraded alreadyUpgradedFault, Throwable cause) {
        super(message, cause);
        this.alreadyUpgradedFault = alreadyUpgradedFault;
    }

    public vmware.vim25.AlreadyUpgraded getFaultInfo() {
        return this.alreadyUpgradedFault;
    }
}
