
package vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-17T16:08:07.413+02:00
 * Generated source version: 2.7.5
 */

@WebFault(name = "AuthMinimumAdminPermissionFault", targetNamespace = "urn:vim25")
public class AuthMinimumAdminPermissionFaultMsg extends Exception {
    
    private vmware.vim25.AuthMinimumAdminPermission authMinimumAdminPermissionFault;

    public AuthMinimumAdminPermissionFaultMsg() {
        super();
    }
    
    public AuthMinimumAdminPermissionFaultMsg(String message) {
        super(message);
    }
    
    public AuthMinimumAdminPermissionFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public AuthMinimumAdminPermissionFaultMsg(String message, vmware.vim25.AuthMinimumAdminPermission authMinimumAdminPermissionFault) {
        super(message);
        this.authMinimumAdminPermissionFault = authMinimumAdminPermissionFault;
    }

    public AuthMinimumAdminPermissionFaultMsg(String message, vmware.vim25.AuthMinimumAdminPermission authMinimumAdminPermissionFault, Throwable cause) {
        super(message, cause);
        this.authMinimumAdminPermissionFault = authMinimumAdminPermissionFault;
    }

    public vmware.vim25.AuthMinimumAdminPermission getFaultInfo() {
        return this.authMinimumAdminPermissionFault;
    }
}
