
package vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-17T16:08:07.870+02:00
 * Generated source version: 2.7.5
 */

@WebFault(name = "CannotAccessLocalSourceFault", targetNamespace = "urn:vim25")
public class CannotAccessLocalSourceFaultMsg extends Exception {
    
    private vmware.vim25.CannotAccessLocalSource cannotAccessLocalSourceFault;

    public CannotAccessLocalSourceFaultMsg() {
        super();
    }
    
    public CannotAccessLocalSourceFaultMsg(String message) {
        super(message);
    }
    
    public CannotAccessLocalSourceFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public CannotAccessLocalSourceFaultMsg(String message, vmware.vim25.CannotAccessLocalSource cannotAccessLocalSourceFault) {
        super(message);
        this.cannotAccessLocalSourceFault = cannotAccessLocalSourceFault;
    }

    public CannotAccessLocalSourceFaultMsg(String message, vmware.vim25.CannotAccessLocalSource cannotAccessLocalSourceFault, Throwable cause) {
        super(message, cause);
        this.cannotAccessLocalSourceFault = cannotAccessLocalSourceFault;
    }

    public vmware.vim25.CannotAccessLocalSource getFaultInfo() {
        return this.cannotAccessLocalSourceFault;
    }
}
