
package vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-17T16:08:07.883+02:00
 * Generated source version: 2.7.5
 */

@WebFault(name = "CannotAccessFileFault", targetNamespace = "urn:vim25")
public class CannotAccessFileFaultMsg extends Exception {
    
    private vmware.vim25.CannotAccessFile cannotAccessFileFault;

    public CannotAccessFileFaultMsg() {
        super();
    }
    
    public CannotAccessFileFaultMsg(String message) {
        super(message);
    }
    
    public CannotAccessFileFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public CannotAccessFileFaultMsg(String message, vmware.vim25.CannotAccessFile cannotAccessFileFault) {
        super(message);
        this.cannotAccessFileFault = cannotAccessFileFault;
    }

    public CannotAccessFileFaultMsg(String message, vmware.vim25.CannotAccessFile cannotAccessFileFault, Throwable cause) {
        super(message, cause);
        this.cannotAccessFileFault = cannotAccessFileFault;
    }

    public vmware.vim25.CannotAccessFile getFaultInfo() {
        return this.cannotAccessFileFault;
    }
}
