
package vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-17T16:08:07.402+02:00
 * Generated source version: 2.7.5
 */

@WebFault(name = "CustomizationFaultFault", targetNamespace = "urn:vim25")
public class CustomizationFaultFaultMsg extends Exception {
    
    private vmware.vim25.CustomizationFault customizationFaultFault;

    public CustomizationFaultFaultMsg() {
        super();
    }
    
    public CustomizationFaultFaultMsg(String message) {
        super(message);
    }
    
    public CustomizationFaultFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public CustomizationFaultFaultMsg(String message, vmware.vim25.CustomizationFault customizationFaultFault) {
        super(message);
        this.customizationFaultFault = customizationFaultFault;
    }

    public CustomizationFaultFaultMsg(String message, vmware.vim25.CustomizationFault customizationFaultFault, Throwable cause) {
        super(message, cause);
        this.customizationFaultFault = customizationFaultFault;
    }

    public vmware.vim25.CustomizationFault getFaultInfo() {
        return this.customizationFaultFault;
    }
}
