
package vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-17T16:08:07.746+02:00
 * Generated source version: 2.7.5
 */

@WebFault(name = "DasConfigFaultFault", targetNamespace = "urn:vim25")
public class DasConfigFaultFaultMsg extends Exception {
    
    private vmware.vim25.DasConfigFault dasConfigFaultFault;

    public DasConfigFaultFaultMsg() {
        super();
    }
    
    public DasConfigFaultFaultMsg(String message) {
        super(message);
    }
    
    public DasConfigFaultFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public DasConfigFaultFaultMsg(String message, vmware.vim25.DasConfigFault dasConfigFaultFault) {
        super(message);
        this.dasConfigFaultFault = dasConfigFaultFault;
    }

    public DasConfigFaultFaultMsg(String message, vmware.vim25.DasConfigFault dasConfigFaultFault, Throwable cause) {
        super(message, cause);
        this.dasConfigFaultFault = dasConfigFaultFault;
    }

    public vmware.vim25.DasConfigFault getFaultInfo() {
        return this.dasConfigFaultFault;
    }
}
