
package vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-17T16:08:07.849+02:00
 * Generated source version: 2.7.5
 */

@WebFault(name = "DatastoreNotWritableOnHostFault", targetNamespace = "urn:vim25")
public class DatastoreNotWritableOnHostFaultMsg extends Exception {
    
    private vmware.vim25.DatastoreNotWritableOnHost datastoreNotWritableOnHostFault;

    public DatastoreNotWritableOnHostFaultMsg() {
        super();
    }
    
    public DatastoreNotWritableOnHostFaultMsg(String message) {
        super(message);
    }
    
    public DatastoreNotWritableOnHostFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public DatastoreNotWritableOnHostFaultMsg(String message, vmware.vim25.DatastoreNotWritableOnHost datastoreNotWritableOnHostFault) {
        super(message);
        this.datastoreNotWritableOnHostFault = datastoreNotWritableOnHostFault;
    }

    public DatastoreNotWritableOnHostFaultMsg(String message, vmware.vim25.DatastoreNotWritableOnHost datastoreNotWritableOnHostFault, Throwable cause) {
        super(message, cause);
        this.datastoreNotWritableOnHostFault = datastoreNotWritableOnHostFault;
    }

    public vmware.vim25.DatastoreNotWritableOnHost getFaultInfo() {
        return this.datastoreNotWritableOnHostFault;
    }
}
