
package vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-17T16:08:07.228+02:00
 * Generated source version: 2.7.5
 */

@WebFault(name = "DuplicateNameFault", targetNamespace = "urn:vim25")
public class DuplicateNameFaultMsg extends Exception {
    
    private vmware.vim25.DuplicateName duplicateNameFault;

    public DuplicateNameFaultMsg() {
        super();
    }
    
    public DuplicateNameFaultMsg(String message) {
        super(message);
    }
    
    public DuplicateNameFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public DuplicateNameFaultMsg(String message, vmware.vim25.DuplicateName duplicateNameFault) {
        super(message);
        this.duplicateNameFault = duplicateNameFault;
    }

    public DuplicateNameFaultMsg(String message, vmware.vim25.DuplicateName duplicateNameFault, Throwable cause) {
        super(message, cause);
        this.duplicateNameFault = duplicateNameFault;
    }

    public vmware.vim25.DuplicateName getFaultInfo() {
        return this.duplicateNameFault;
    }
}
