
package vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-17T16:08:07.331+02:00
 * Generated source version: 2.7.5
 */

@WebFault(name = "DvsFaultFault", targetNamespace = "urn:vim25")
public class DvsFaultFaultMsg extends Exception {
    
    private vmware.vim25.DvsFault dvsFaultFault;

    public DvsFaultFaultMsg() {
        super();
    }
    
    public DvsFaultFaultMsg(String message) {
        super(message);
    }
    
    public DvsFaultFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public DvsFaultFaultMsg(String message, vmware.vim25.DvsFault dvsFaultFault) {
        super(message);
        this.dvsFaultFault = dvsFaultFault;
    }

    public DvsFaultFaultMsg(String message, vmware.vim25.DvsFault dvsFaultFault, Throwable cause) {
        super(message, cause);
        this.dvsFaultFault = dvsFaultFault;
    }

    public vmware.vim25.DvsFault getFaultInfo() {
        return this.dvsFaultFault;
    }
}
