
package vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-17T16:08:07.391+02:00
 * Generated source version: 2.7.5
 */

@WebFault(name = "DvsNotAuthorizedFault", targetNamespace = "urn:vim25")
public class DvsNotAuthorizedFaultMsg extends Exception {
    
    private vmware.vim25.DvsNotAuthorized dvsNotAuthorizedFault;

    public DvsNotAuthorizedFaultMsg() {
        super();
    }
    
    public DvsNotAuthorizedFaultMsg(String message) {
        super(message);
    }
    
    public DvsNotAuthorizedFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public DvsNotAuthorizedFaultMsg(String message, vmware.vim25.DvsNotAuthorized dvsNotAuthorizedFault) {
        super(message);
        this.dvsNotAuthorizedFault = dvsNotAuthorizedFault;
    }

    public DvsNotAuthorizedFaultMsg(String message, vmware.vim25.DvsNotAuthorized dvsNotAuthorizedFault, Throwable cause) {
        super(message, cause);
        this.dvsNotAuthorizedFault = dvsNotAuthorizedFault;
    }

    public vmware.vim25.DvsNotAuthorized getFaultInfo() {
        return this.dvsNotAuthorizedFault;
    }
}
