
package vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-17T16:08:07.276+02:00
 * Generated source version: 2.7.5
 */

@WebFault(name = "FileFaultFault", targetNamespace = "urn:vim25")
public class FileFaultFaultMsg extends Exception {
    
    private vmware.vim25.FileFault fileFaultFault;

    public FileFaultFaultMsg() {
        super();
    }
    
    public FileFaultFaultMsg(String message) {
        super(message);
    }
    
    public FileFaultFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public FileFaultFaultMsg(String message, vmware.vim25.FileFault fileFaultFault) {
        super(message);
        this.fileFaultFault = fileFaultFault;
    }

    public FileFaultFaultMsg(String message, vmware.vim25.FileFault fileFaultFault, Throwable cause) {
        super(message, cause);
        this.fileFaultFault = fileFaultFault;
    }

    public vmware.vim25.FileFault getFaultInfo() {
        return this.fileFaultFault;
    }
}
