
package vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-17T16:08:07.865+02:00
 * Generated source version: 2.7.5
 */

@WebFault(name = "FileNotFoundFault", targetNamespace = "urn:vim25")
public class FileNotFoundFaultMsg extends Exception {
    
    private vmware.vim25.FileNotFound fileNotFoundFault;

    public FileNotFoundFaultMsg() {
        super();
    }
    
    public FileNotFoundFaultMsg(String message) {
        super(message);
    }
    
    public FileNotFoundFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public FileNotFoundFaultMsg(String message, vmware.vim25.FileNotFound fileNotFoundFault) {
        super(message);
        this.fileNotFoundFault = fileNotFoundFault;
    }

    public FileNotFoundFaultMsg(String message, vmware.vim25.FileNotFound fileNotFoundFault, Throwable cause) {
        super(message, cause);
        this.fileNotFoundFault = fileNotFoundFault;
    }

    public vmware.vim25.FileNotFound getFaultInfo() {
        return this.fileNotFoundFault;
    }
}
