
package vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-17T16:08:07.244+02:00
 * Generated source version: 2.7.5
 */

@WebFault(name = "HostConfigFaultFault", targetNamespace = "urn:vim25")
public class HostConfigFaultFaultMsg extends Exception {
    
    private vmware.vim25.HostConfigFault hostConfigFaultFault;

    public HostConfigFaultFaultMsg() {
        super();
    }
    
    public HostConfigFaultFaultMsg(String message) {
        super(message);
    }
    
    public HostConfigFaultFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public HostConfigFaultFaultMsg(String message, vmware.vim25.HostConfigFault hostConfigFaultFault) {
        super(message);
        this.hostConfigFaultFault = hostConfigFaultFault;
    }

    public HostConfigFaultFaultMsg(String message, vmware.vim25.HostConfigFault hostConfigFaultFault, Throwable cause) {
        super(message, cause);
        this.hostConfigFaultFault = hostConfigFaultFault;
    }

    public vmware.vim25.HostConfigFault getFaultInfo() {
        return this.hostConfigFaultFault;
    }
}
