
package vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-17T16:08:07.856+02:00
 * Generated source version: 2.7.5
 */

@WebFault(name = "HostIncompatibleForRecordReplayFault", targetNamespace = "urn:vim25")
public class HostIncompatibleForRecordReplayFaultMsg extends Exception {
    
    private vmware.vim25.HostIncompatibleForRecordReplay hostIncompatibleForRecordReplayFault;

    public HostIncompatibleForRecordReplayFaultMsg() {
        super();
    }
    
    public HostIncompatibleForRecordReplayFaultMsg(String message) {
        super(message);
    }
    
    public HostIncompatibleForRecordReplayFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public HostIncompatibleForRecordReplayFaultMsg(String message, vmware.vim25.HostIncompatibleForRecordReplay hostIncompatibleForRecordReplayFault) {
        super(message);
        this.hostIncompatibleForRecordReplayFault = hostIncompatibleForRecordReplayFault;
    }

    public HostIncompatibleForRecordReplayFaultMsg(String message, vmware.vim25.HostIncompatibleForRecordReplay hostIncompatibleForRecordReplayFault, Throwable cause) {
        super(message, cause);
        this.hostIncompatibleForRecordReplayFault = hostIncompatibleForRecordReplayFault;
    }

    public vmware.vim25.HostIncompatibleForRecordReplay getFaultInfo() {
        return this.hostIncompatibleForRecordReplayFault;
    }
}
