
package vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-17T16:08:07.878+02:00
 * Generated source version: 2.7.5
 */

@WebFault(name = "HostConfigFailedFault", targetNamespace = "urn:vim25")
public class HostConfigFailedFaultMsg extends Exception {
    
    private vmware.vim25.HostConfigFailed hostConfigFailedFault;

    public HostConfigFailedFaultMsg() {
        super();
    }
    
    public HostConfigFailedFaultMsg(String message) {
        super(message);
    }
    
    public HostConfigFailedFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public HostConfigFailedFaultMsg(String message, vmware.vim25.HostConfigFailed hostConfigFailedFault) {
        super(message);
        this.hostConfigFailedFault = hostConfigFailedFault;
    }

    public HostConfigFailedFaultMsg(String message, vmware.vim25.HostConfigFailed hostConfigFailedFault, Throwable cause) {
        super(message, cause);
        this.hostConfigFailedFault = hostConfigFailedFault;
    }

    public vmware.vim25.HostConfigFailed getFaultInfo() {
        return this.hostConfigFailedFault;
    }
}
