
package vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-17T16:08:07.785+02:00
 * Generated source version: 2.7.5
 */

@WebFault(name = "HostPowerOpFailedFault", targetNamespace = "urn:vim25")
public class HostPowerOpFailedFaultMsg extends Exception {
    
    private vmware.vim25.HostPowerOpFailed hostPowerOpFailedFault;

    public HostPowerOpFailedFaultMsg() {
        super();
    }
    
    public HostPowerOpFailedFaultMsg(String message) {
        super(message);
    }
    
    public HostPowerOpFailedFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public HostPowerOpFailedFaultMsg(String message, vmware.vim25.HostPowerOpFailed hostPowerOpFailedFault) {
        super(message);
        this.hostPowerOpFailedFault = hostPowerOpFailedFault;
    }

    public HostPowerOpFailedFaultMsg(String message, vmware.vim25.HostPowerOpFailed hostPowerOpFailedFault, Throwable cause) {
        super(message, cause);
        this.hostPowerOpFailedFault = hostPowerOpFailedFault;
    }

    public vmware.vim25.HostPowerOpFailed getFaultInfo() {
        return this.hostPowerOpFailedFault;
    }
}
