
package vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-17T16:08:07.484+02:00
 * Generated source version: 2.7.5
 */

@WebFault(name = "InaccessibleDatastoreFault", targetNamespace = "urn:vim25")
public class InaccessibleDatastoreFaultMsg extends Exception {
    
    private vmware.vim25.InaccessibleDatastore inaccessibleDatastoreFault;

    public InaccessibleDatastoreFaultMsg() {
        super();
    }
    
    public InaccessibleDatastoreFaultMsg(String message) {
        super(message);
    }
    
    public InaccessibleDatastoreFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public InaccessibleDatastoreFaultMsg(String message, vmware.vim25.InaccessibleDatastore inaccessibleDatastoreFault) {
        super(message);
        this.inaccessibleDatastoreFault = inaccessibleDatastoreFault;
    }

    public InaccessibleDatastoreFaultMsg(String message, vmware.vim25.InaccessibleDatastore inaccessibleDatastoreFault, Throwable cause) {
        super(message, cause);
        this.inaccessibleDatastoreFault = inaccessibleDatastoreFault;
    }

    public vmware.vim25.InaccessibleDatastore getFaultInfo() {
        return this.inaccessibleDatastoreFault;
    }
}
