
package vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-17T16:08:07.267+02:00
 * Generated source version: 2.7.5
 */

@WebFault(name = "InsufficientResourcesFaultFault", targetNamespace = "urn:vim25")
public class InsufficientResourcesFaultFaultMsg extends Exception {
    
    private vmware.vim25.InsufficientResourcesFault insufficientResourcesFaultFault;

    public InsufficientResourcesFaultFaultMsg() {
        super();
    }
    
    public InsufficientResourcesFaultFaultMsg(String message) {
        super(message);
    }
    
    public InsufficientResourcesFaultFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public InsufficientResourcesFaultFaultMsg(String message, vmware.vim25.InsufficientResourcesFault insufficientResourcesFaultFault) {
        super(message);
        this.insufficientResourcesFaultFault = insufficientResourcesFaultFault;
    }

    public InsufficientResourcesFaultFaultMsg(String message, vmware.vim25.InsufficientResourcesFault insufficientResourcesFaultFault, Throwable cause) {
        super(message, cause);
        this.insufficientResourcesFaultFault = insufficientResourcesFaultFault;
    }

    public vmware.vim25.InsufficientResourcesFault getFaultInfo() {
        return this.insufficientResourcesFaultFault;
    }
}
