
package vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-17T16:08:07.291+02:00
 * Generated source version: 2.7.5
 */

@WebFault(name = "InvalidLocaleFault", targetNamespace = "urn:vim25")
public class InvalidLocaleFaultMsg extends Exception {
    
    private vmware.vim25.InvalidLocale invalidLocaleFault;

    public InvalidLocaleFaultMsg() {
        super();
    }
    
    public InvalidLocaleFaultMsg(String message) {
        super(message);
    }
    
    public InvalidLocaleFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidLocaleFaultMsg(String message, vmware.vim25.InvalidLocale invalidLocaleFault) {
        super(message);
        this.invalidLocaleFault = invalidLocaleFault;
    }

    public InvalidLocaleFaultMsg(String message, vmware.vim25.InvalidLocale invalidLocaleFault, Throwable cause) {
        super(message, cause);
        this.invalidLocaleFault = invalidLocaleFault;
    }

    public vmware.vim25.InvalidLocale getFaultInfo() {
        return this.invalidLocaleFault;
    }
}
