
package vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-17T16:08:07.867+02:00
 * Generated source version: 2.7.5
 */

@WebFault(name = "InvalidLicenseFault", targetNamespace = "urn:vim25")
public class InvalidLicenseFaultMsg extends Exception {
    
    private vmware.vim25.InvalidLicense invalidLicenseFault;

    public InvalidLicenseFaultMsg() {
        super();
    }
    
    public InvalidLicenseFaultMsg(String message) {
        super(message);
    }
    
    public InvalidLicenseFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidLicenseFaultMsg(String message, vmware.vim25.InvalidLicense invalidLicenseFault) {
        super(message);
        this.invalidLicenseFault = invalidLicenseFault;
    }

    public InvalidLicenseFaultMsg(String message, vmware.vim25.InvalidLicense invalidLicenseFault, Throwable cause) {
        super(message, cause);
        this.invalidLicenseFault = invalidLicenseFault;
    }

    public vmware.vim25.InvalidLicense getFaultInfo() {
        return this.invalidLicenseFault;
    }
}
