
package vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-17T16:08:07.852+02:00
 * Generated source version: 2.7.5
 */

@WebFault(name = "InvalidHostStateFault", targetNamespace = "urn:vim25")
public class InvalidHostStateFaultMsg extends Exception {
    
    private vmware.vim25.InvalidHostState invalidHostStateFault;

    public InvalidHostStateFaultMsg() {
        super();
    }
    
    public InvalidHostStateFaultMsg(String message) {
        super(message);
    }
    
    public InvalidHostStateFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidHostStateFaultMsg(String message, vmware.vim25.InvalidHostState invalidHostStateFault) {
        super(message);
        this.invalidHostStateFault = invalidHostStateFault;
    }

    public InvalidHostStateFaultMsg(String message, vmware.vim25.InvalidHostState invalidHostStateFault, Throwable cause) {
        super(message, cause);
        this.invalidHostStateFault = invalidHostStateFault;
    }

    public vmware.vim25.InvalidHostState getFaultInfo() {
        return this.invalidHostStateFault;
    }
}
