
package vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-17T16:08:07.771+02:00
 * Generated source version: 2.7.5
 */

@WebFault(name = "InvalidFolderFault", targetNamespace = "urn:vim25")
public class InvalidFolderFaultMsg extends Exception {
    
    private vmware.vim25.InvalidFolder invalidFolderFault;

    public InvalidFolderFaultMsg() {
        super();
    }
    
    public InvalidFolderFaultMsg(String message) {
        super(message);
    }
    
    public InvalidFolderFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidFolderFaultMsg(String message, vmware.vim25.InvalidFolder invalidFolderFault) {
        super(message);
        this.invalidFolderFault = invalidFolderFault;
    }

    public InvalidFolderFaultMsg(String message, vmware.vim25.InvalidFolder invalidFolderFault, Throwable cause) {
        super(message, cause);
        this.invalidFolderFault = invalidFolderFault;
    }

    public vmware.vim25.InvalidFolder getFaultInfo() {
        return this.invalidFolderFault;
    }
}
