
package vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-17T16:08:07.750+02:00
 * Generated source version: 2.7.5
 */

@WebFault(name = "InvalidPowerStateFault", targetNamespace = "urn:vim25")
public class InvalidPowerStateFaultMsg extends Exception {
    
    private vmware.vim25.InvalidPowerState invalidPowerStateFault;

    public InvalidPowerStateFaultMsg() {
        super();
    }
    
    public InvalidPowerStateFaultMsg(String message) {
        super(message);
    }
    
    public InvalidPowerStateFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidPowerStateFaultMsg(String message, vmware.vim25.InvalidPowerState invalidPowerStateFault) {
        super(message);
        this.invalidPowerStateFault = invalidPowerStateFault;
    }

    public InvalidPowerStateFaultMsg(String message, vmware.vim25.InvalidPowerState invalidPowerStateFault, Throwable cause) {
        super(message, cause);
        this.invalidPowerStateFault = invalidPowerStateFault;
    }

    public vmware.vim25.InvalidPowerState getFaultInfo() {
        return this.invalidPowerStateFault;
    }
}
