
package vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-17T16:08:07.408+02:00
 * Generated source version: 2.7.5
 */

@WebFault(name = "InvalidDatastoreFault", targetNamespace = "urn:vim25")
public class InvalidDatastoreFaultMsg extends Exception {
    
    private vmware.vim25.InvalidDatastore invalidDatastoreFault;

    public InvalidDatastoreFaultMsg() {
        super();
    }
    
    public InvalidDatastoreFaultMsg(String message) {
        super(message);
    }
    
    public InvalidDatastoreFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidDatastoreFaultMsg(String message, vmware.vim25.InvalidDatastore invalidDatastoreFault) {
        super(message);
        this.invalidDatastoreFault = invalidDatastoreFault;
    }

    public InvalidDatastoreFaultMsg(String message, vmware.vim25.InvalidDatastore invalidDatastoreFault, Throwable cause) {
        super(message, cause);
        this.invalidDatastoreFault = invalidDatastoreFault;
    }

    public vmware.vim25.InvalidDatastore getFaultInfo() {
        return this.invalidDatastoreFault;
    }
}
