
package vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-17T16:08:07.762+02:00
 * Generated source version: 2.7.5
 */

@WebFault(name = "InvalidBundleFault", targetNamespace = "urn:vim25")
public class InvalidBundleFaultMsg extends Exception {
    
    private vmware.vim25.InvalidBundle invalidBundleFault;

    public InvalidBundleFaultMsg() {
        super();
    }
    
    public InvalidBundleFaultMsg(String message) {
        super(message);
    }
    
    public InvalidBundleFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidBundleFaultMsg(String message, vmware.vim25.InvalidBundle invalidBundleFault) {
        super(message);
        this.invalidBundleFault = invalidBundleFault;
    }

    public InvalidBundleFaultMsg(String message, vmware.vim25.InvalidBundle invalidBundleFault, Throwable cause) {
        super(message, cause);
        this.invalidBundleFault = invalidBundleFault;
    }

    public vmware.vim25.InvalidBundle getFaultInfo() {
        return this.invalidBundleFault;
    }
}
