
package vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-17T16:08:07.803+02:00
 * Generated source version: 2.7.5
 */

@WebFault(name = "InvalidEventFault", targetNamespace = "urn:vim25")
public class InvalidEventFaultMsg extends Exception {
    
    private vmware.vim25.InvalidEvent invalidEventFault;

    public InvalidEventFaultMsg() {
        super();
    }
    
    public InvalidEventFaultMsg(String message) {
        super(message);
    }
    
    public InvalidEventFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidEventFaultMsg(String message, vmware.vim25.InvalidEvent invalidEventFault) {
        super(message);
        this.invalidEventFault = invalidEventFault;
    }

    public InvalidEventFaultMsg(String message, vmware.vim25.InvalidEvent invalidEventFault, Throwable cause) {
        super(message, cause);
        this.invalidEventFault = invalidEventFault;
    }

    public vmware.vim25.InvalidEvent getFaultInfo() {
        return this.invalidEventFault;
    }
}
