
package vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-17T16:08:07.465+02:00
 * Generated source version: 2.7.5
 */

@WebFault(name = "InvalidArgumentFault", targetNamespace = "urn:vim25")
public class InvalidArgumentFaultMsg extends Exception {
    
    private vmware.vim25.InvalidArgument invalidArgumentFault;

    public InvalidArgumentFaultMsg() {
        super();
    }
    
    public InvalidArgumentFaultMsg(String message) {
        super(message);
    }
    
    public InvalidArgumentFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidArgumentFaultMsg(String message, vmware.vim25.InvalidArgument invalidArgumentFault) {
        super(message);
        this.invalidArgumentFault = invalidArgumentFault;
    }

    public InvalidArgumentFaultMsg(String message, vmware.vim25.InvalidArgument invalidArgumentFault, Throwable cause) {
        super(message, cause);
        this.invalidArgumentFault = invalidArgumentFault;
    }

    public vmware.vim25.InvalidArgument getFaultInfo() {
        return this.invalidArgumentFault;
    }
}
