
package vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-17T16:08:07.307+02:00
 * Generated source version: 2.7.5
 */

@WebFault(name = "InvalidLoginFault", targetNamespace = "urn:vim25")
public class InvalidLoginFaultMsg extends Exception {
    
    private vmware.vim25.InvalidLogin invalidLoginFault;

    public InvalidLoginFaultMsg() {
        super();
    }
    
    public InvalidLoginFaultMsg(String message) {
        super(message);
    }
    
    public InvalidLoginFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidLoginFaultMsg(String message, vmware.vim25.InvalidLogin invalidLoginFault) {
        super(message);
        this.invalidLoginFault = invalidLoginFault;
    }

    public InvalidLoginFaultMsg(String message, vmware.vim25.InvalidLogin invalidLoginFault, Throwable cause) {
        super(message, cause);
        this.invalidLoginFault = invalidLoginFault;
    }

    public vmware.vim25.InvalidLogin getFaultInfo() {
        return this.invalidLoginFault;
    }
}
