
package vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-17T16:08:07.350+02:00
 * Generated source version: 2.7.5
 */

@WebFault(name = "InvalidNameFault", targetNamespace = "urn:vim25")
public class InvalidNameFaultMsg extends Exception {
    
    private vmware.vim25.InvalidName invalidNameFault;

    public InvalidNameFaultMsg() {
        super();
    }
    
    public InvalidNameFaultMsg(String message) {
        super(message);
    }
    
    public InvalidNameFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidNameFaultMsg(String message, vmware.vim25.InvalidName invalidNameFault) {
        super(message);
        this.invalidNameFault = invalidNameFault;
    }

    public InvalidNameFaultMsg(String message, vmware.vim25.InvalidName invalidNameFault, Throwable cause) {
        super(message, cause);
        this.invalidNameFault = invalidNameFault;
    }

    public vmware.vim25.InvalidName getFaultInfo() {
        return this.invalidNameFault;
    }
}
