
package vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-17T16:08:07.479+02:00
 * Generated source version: 2.7.5
 */

@WebFault(name = "IORMNotSupportedHostOnDatastoreFault", targetNamespace = "urn:vim25")
public class IORMNotSupportedHostOnDatastoreFaultMsg extends Exception {
    
    private vmware.vim25.IORMNotSupportedHostOnDatastore iormNotSupportedHostOnDatastoreFault;

    public IORMNotSupportedHostOnDatastoreFaultMsg() {
        super();
    }
    
    public IORMNotSupportedHostOnDatastoreFaultMsg(String message) {
        super(message);
    }
    
    public IORMNotSupportedHostOnDatastoreFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public IORMNotSupportedHostOnDatastoreFaultMsg(String message, vmware.vim25.IORMNotSupportedHostOnDatastore iormNotSupportedHostOnDatastoreFault) {
        super(message);
        this.iormNotSupportedHostOnDatastoreFault = iormNotSupportedHostOnDatastoreFault;
    }

    public IORMNotSupportedHostOnDatastoreFaultMsg(String message, vmware.vim25.IORMNotSupportedHostOnDatastore iormNotSupportedHostOnDatastoreFault, Throwable cause) {
        super(message, cause);
        this.iormNotSupportedHostOnDatastoreFault = iormNotSupportedHostOnDatastoreFault;
    }

    public vmware.vim25.IORMNotSupportedHostOnDatastore getFaultInfo() {
        return this.iormNotSupportedHostOnDatastoreFault;
    }
}
