
package vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-17T16:08:07.450+02:00
 * Generated source version: 2.7.5
 */

@WebFault(name = "LicenseEntityNotFoundFault", targetNamespace = "urn:vim25")
public class LicenseEntityNotFoundFaultMsg extends Exception {
    
    private vmware.vim25.LicenseEntityNotFound licenseEntityNotFoundFault;

    public LicenseEntityNotFoundFaultMsg() {
        super();
    }
    
    public LicenseEntityNotFoundFaultMsg(String message) {
        super(message);
    }
    
    public LicenseEntityNotFoundFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public LicenseEntityNotFoundFaultMsg(String message, vmware.vim25.LicenseEntityNotFound licenseEntityNotFoundFault) {
        super(message);
        this.licenseEntityNotFoundFault = licenseEntityNotFoundFault;
    }

    public LicenseEntityNotFoundFaultMsg(String message, vmware.vim25.LicenseEntityNotFound licenseEntityNotFoundFault, Throwable cause) {
        super(message, cause);
        this.licenseEntityNotFoundFault = licenseEntityNotFoundFault;
    }

    public vmware.vim25.LicenseEntityNotFound getFaultInfo() {
        return this.licenseEntityNotFoundFault;
    }
}
