
package vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-17T16:08:07.440+02:00
 * Generated source version: 2.7.5
 */

@WebFault(name = "LicenseServerUnavailableFault", targetNamespace = "urn:vim25")
public class LicenseServerUnavailableFaultMsg extends Exception {
    
    private vmware.vim25.LicenseServerUnavailable licenseServerUnavailableFault;

    public LicenseServerUnavailableFaultMsg() {
        super();
    }
    
    public LicenseServerUnavailableFaultMsg(String message) {
        super(message);
    }
    
    public LicenseServerUnavailableFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public LicenseServerUnavailableFaultMsg(String message, vmware.vim25.LicenseServerUnavailable licenseServerUnavailableFault) {
        super(message);
        this.licenseServerUnavailableFault = licenseServerUnavailableFault;
    }

    public LicenseServerUnavailableFaultMsg(String message, vmware.vim25.LicenseServerUnavailable licenseServerUnavailableFault, Throwable cause) {
        super(message, cause);
        this.licenseServerUnavailableFault = licenseServerUnavailableFault;
    }

    public vmware.vim25.LicenseServerUnavailable getFaultInfo() {
        return this.licenseServerUnavailableFault;
    }
}
