
package vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-17T16:08:07.396+02:00
 * Generated source version: 2.7.5
 */

@WebFault(name = "LimitExceededFault", targetNamespace = "urn:vim25")
public class LimitExceededFaultMsg extends Exception {
    
    private vmware.vim25.LimitExceeded limitExceededFault;

    public LimitExceededFaultMsg() {
        super();
    }
    
    public LimitExceededFaultMsg(String message) {
        super(message);
    }
    
    public LimitExceededFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public LimitExceededFaultMsg(String message, vmware.vim25.LimitExceeded limitExceededFault) {
        super(message);
        this.limitExceededFault = limitExceededFault;
    }

    public LimitExceededFaultMsg(String message, vmware.vim25.LimitExceeded limitExceededFault, Throwable cause) {
        super(message, cause);
        this.limitExceededFault = limitExceededFault;
    }

    public vmware.vim25.LimitExceeded getFaultInfo() {
        return this.limitExceededFault;
    }
}
