
package vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-17T16:08:07.754+02:00
 * Generated source version: 2.7.5
 */

@WebFault(name = "LogBundlingFailedFault", targetNamespace = "urn:vim25")
public class LogBundlingFailedFaultMsg extends Exception {
    
    private vmware.vim25.LogBundlingFailed logBundlingFailedFault;

    public LogBundlingFailedFaultMsg() {
        super();
    }
    
    public LogBundlingFailedFaultMsg(String message) {
        super(message);
    }
    
    public LogBundlingFailedFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public LogBundlingFailedFaultMsg(String message, vmware.vim25.LogBundlingFailed logBundlingFailedFault) {
        super(message);
        this.logBundlingFailedFault = logBundlingFailedFault;
    }

    public LogBundlingFailedFaultMsg(String message, vmware.vim25.LogBundlingFailed logBundlingFailedFault, Throwable cause) {
        super(message, cause);
        this.logBundlingFailedFault = logBundlingFailedFault;
    }

    public vmware.vim25.LogBundlingFailed getFaultInfo() {
        return this.logBundlingFailedFault;
    }
}
