
package vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-17T16:08:07.470+02:00
 * Generated source version: 2.7.5
 */

@WebFault(name = "MigrationFaultFault", targetNamespace = "urn:vim25")
public class MigrationFaultFaultMsg extends Exception {
    
    private vmware.vim25.MigrationFault migrationFaultFault;

    public MigrationFaultFaultMsg() {
        super();
    }
    
    public MigrationFaultFaultMsg(String message) {
        super(message);
    }
    
    public MigrationFaultFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public MigrationFaultFaultMsg(String message, vmware.vim25.MigrationFault migrationFaultFault) {
        super(message);
        this.migrationFaultFault = migrationFaultFault;
    }

    public MigrationFaultFaultMsg(String message, vmware.vim25.MigrationFault migrationFaultFault, Throwable cause) {
        super(message, cause);
        this.migrationFaultFault = migrationFaultFault;
    }

    public vmware.vim25.MigrationFault getFaultInfo() {
        return this.migrationFaultFault;
    }
}
