
package vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-17T16:08:07.758+02:00
 * Generated source version: 2.7.5
 */

@WebFault(name = "MismatchedBundleFault", targetNamespace = "urn:vim25")
public class MismatchedBundleFaultMsg extends Exception {
    
    private vmware.vim25.MismatchedBundle mismatchedBundleFault;

    public MismatchedBundleFaultMsg() {
        super();
    }
    
    public MismatchedBundleFaultMsg(String message) {
        super(message);
    }
    
    public MismatchedBundleFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public MismatchedBundleFaultMsg(String message, vmware.vim25.MismatchedBundle mismatchedBundleFault) {
        super(message);
        this.mismatchedBundleFault = mismatchedBundleFault;
    }

    public MismatchedBundleFaultMsg(String message, vmware.vim25.MismatchedBundle mismatchedBundleFault, Throwable cause) {
        super(message, cause);
        this.mismatchedBundleFault = mismatchedBundleFault;
    }

    public vmware.vim25.MismatchedBundle getFaultInfo() {
        return this.mismatchedBundleFault;
    }
}
