
package vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-17T16:08:07.284+02:00
 * Generated source version: 2.7.5
 */

@WebFault(name = "NoClientCertificateFault", targetNamespace = "urn:vim25")
public class NoClientCertificateFaultMsg extends Exception {
    
    private vmware.vim25.NoClientCertificate noClientCertificateFault;

    public NoClientCertificateFaultMsg() {
        super();
    }
    
    public NoClientCertificateFaultMsg(String message) {
        super(message);
    }
    
    public NoClientCertificateFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public NoClientCertificateFaultMsg(String message, vmware.vim25.NoClientCertificate noClientCertificateFault) {
        super(message);
        this.noClientCertificateFault = noClientCertificateFault;
    }

    public NoClientCertificateFaultMsg(String message, vmware.vim25.NoClientCertificate noClientCertificateFault, Throwable cause) {
        super(message, cause);
        this.noClientCertificateFault = noClientCertificateFault;
    }

    public vmware.vim25.NoClientCertificate getFaultInfo() {
        return this.noClientCertificateFault;
    }
}
