
package vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-17T16:08:07.831+02:00
 * Generated source version: 2.7.5
 */

@WebFault(name = "NoDiskSpaceFault", targetNamespace = "urn:vim25")
public class NoDiskSpaceFaultMsg extends Exception {
    
    private vmware.vim25.NoDiskSpace noDiskSpaceFault;

    public NoDiskSpaceFaultMsg() {
        super();
    }
    
    public NoDiskSpaceFaultMsg(String message) {
        super(message);
    }
    
    public NoDiskSpaceFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public NoDiskSpaceFaultMsg(String message, vmware.vim25.NoDiskSpace noDiskSpaceFault) {
        super(message);
        this.noDiskSpaceFault = noDiskSpaceFault;
    }

    public NoDiskSpaceFaultMsg(String message, vmware.vim25.NoDiskSpace noDiskSpaceFault, Throwable cause) {
        super(message, cause);
        this.noDiskSpaceFault = noDiskSpaceFault;
    }

    public vmware.vim25.NoDiskSpace getFaultInfo() {
        return this.noDiskSpaceFault;
    }
}
