
package vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-17T16:08:07.299+02:00
 * Generated source version: 2.7.5
 */

@WebFault(name = "NotFoundFault", targetNamespace = "urn:vim25")
public class NotFoundFaultMsg extends Exception {
    
    private vmware.vim25.NotFound notFoundFault;

    public NotFoundFaultMsg() {
        super();
    }
    
    public NotFoundFaultMsg(String message) {
        super(message);
    }
    
    public NotFoundFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public NotFoundFaultMsg(String message, vmware.vim25.NotFound notFoundFault) {
        super(message);
        this.notFoundFault = notFoundFault;
    }

    public NotFoundFaultMsg(String message, vmware.vim25.NotFound notFoundFault, Throwable cause) {
        super(message, cause);
        this.notFoundFault = notFoundFault;
    }

    public vmware.vim25.NotFound getFaultInfo() {
        return this.notFoundFault;
    }
}
