
package vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-17T16:08:07.780+02:00
 * Generated source version: 2.7.5
 */

@WebFault(name = "NotSupportedFault", targetNamespace = "urn:vim25")
public class NotSupportedFaultMsg extends Exception {
    
    private vmware.vim25.NotSupported notSupportedFault;

    public NotSupportedFaultMsg() {
        super();
    }
    
    public NotSupportedFaultMsg(String message) {
        super(message);
    }
    
    public NotSupportedFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public NotSupportedFaultMsg(String message, vmware.vim25.NotSupported notSupportedFault) {
        super(message);
        this.notSupportedFault = notSupportedFault;
    }

    public NotSupportedFaultMsg(String message, vmware.vim25.NotSupported notSupportedFault, Throwable cause) {
        super(message, cause);
        this.notSupportedFault = notSupportedFault;
    }

    public vmware.vim25.NotSupported getFaultInfo() {
        return this.notSupportedFault;
    }
}
