
package vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-17T16:08:07.435+02:00
 * Generated source version: 2.7.5
 */

@WebFault(name = "OutOfBoundsFault", targetNamespace = "urn:vim25")
public class OutOfBoundsFaultMsg extends Exception {
    
    private vmware.vim25.OutOfBounds outOfBoundsFault;

    public OutOfBoundsFaultMsg() {
        super();
    }
    
    public OutOfBoundsFaultMsg(String message) {
        super(message);
    }
    
    public OutOfBoundsFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public OutOfBoundsFaultMsg(String message, vmware.vim25.OutOfBounds outOfBoundsFault) {
        super(message);
        this.outOfBoundsFault = outOfBoundsFault;
    }

    public OutOfBoundsFaultMsg(String message, vmware.vim25.OutOfBounds outOfBoundsFault, Throwable cause) {
        super(message, cause);
        this.outOfBoundsFault = outOfBoundsFault;
    }

    public vmware.vim25.OutOfBounds getFaultInfo() {
        return this.outOfBoundsFault;
    }
}
