
package vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-17T16:08:07.821+02:00
 * Generated source version: 2.7.5
 */

@WebFault(name = "PatchNotApplicableFault", targetNamespace = "urn:vim25")
public class PatchNotApplicableFaultMsg extends Exception {
    
    private vmware.vim25.PatchNotApplicable patchNotApplicableFault;

    public PatchNotApplicableFaultMsg() {
        super();
    }
    
    public PatchNotApplicableFaultMsg(String message) {
        super(message);
    }
    
    public PatchNotApplicableFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public PatchNotApplicableFaultMsg(String message, vmware.vim25.PatchNotApplicable patchNotApplicableFault) {
        super(message);
        this.patchNotApplicableFault = patchNotApplicableFault;
    }

    public PatchNotApplicableFaultMsg(String message, vmware.vim25.PatchNotApplicable patchNotApplicableFault, Throwable cause) {
        super(message, cause);
        this.patchNotApplicableFault = patchNotApplicableFault;
    }

    public vmware.vim25.PatchNotApplicable getFaultInfo() {
        return this.patchNotApplicableFault;
    }
}
