
package vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-17T16:08:07.826+02:00
 * Generated source version: 2.7.5
 */

@WebFault(name = "PatchInstallFailedFault", targetNamespace = "urn:vim25")
public class PatchInstallFailedFaultMsg extends Exception {
    
    private vmware.vim25.PatchInstallFailed patchInstallFailedFault;

    public PatchInstallFailedFaultMsg() {
        super();
    }
    
    public PatchInstallFailedFaultMsg(String message) {
        super(message);
    }
    
    public PatchInstallFailedFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public PatchInstallFailedFaultMsg(String message, vmware.vim25.PatchInstallFailed patchInstallFailedFault) {
        super(message);
        this.patchInstallFailedFault = patchInstallFailedFault;
    }

    public PatchInstallFailedFaultMsg(String message, vmware.vim25.PatchInstallFailed patchInstallFailedFault, Throwable cause) {
        super(message, cause);
        this.patchInstallFailedFault = patchInstallFailedFault;
    }

    public vmware.vim25.PatchInstallFailed getFaultInfo() {
        return this.patchInstallFailedFault;
    }
}
