
package vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-17T16:08:07.812+02:00
 * Generated source version: 2.7.5
 */

@WebFault(name = "PatchMetadataInvalidFault", targetNamespace = "urn:vim25")
public class PatchMetadataInvalidFaultMsg extends Exception {
    
    private vmware.vim25.PatchMetadataInvalid patchMetadataInvalidFault;

    public PatchMetadataInvalidFaultMsg() {
        super();
    }
    
    public PatchMetadataInvalidFaultMsg(String message) {
        super(message);
    }
    
    public PatchMetadataInvalidFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public PatchMetadataInvalidFaultMsg(String message, vmware.vim25.PatchMetadataInvalid patchMetadataInvalidFault) {
        super(message);
        this.patchMetadataInvalidFault = patchMetadataInvalidFault;
    }

    public PatchMetadataInvalidFaultMsg(String message, vmware.vim25.PatchMetadataInvalid patchMetadataInvalidFault, Throwable cause) {
        super(message, cause);
        this.patchMetadataInvalidFault = patchMetadataInvalidFault;
    }

    public vmware.vim25.PatchMetadataInvalid getFaultInfo() {
        return this.patchMetadataInvalidFault;
    }
}
