
package vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-17T16:08:07.367+02:00
 * Generated source version: 2.7.5
 */

@WebFault(name = "PlatformConfigFaultFault", targetNamespace = "urn:vim25")
public class PlatformConfigFaultFaultMsg extends Exception {
    
    private vmware.vim25.PlatformConfigFault platformConfigFaultFault;

    public PlatformConfigFaultFaultMsg() {
        super();
    }
    
    public PlatformConfigFaultFaultMsg(String message) {
        super(message);
    }
    
    public PlatformConfigFaultFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public PlatformConfigFaultFaultMsg(String message, vmware.vim25.PlatformConfigFault platformConfigFaultFault) {
        super(message);
        this.platformConfigFaultFault = platformConfigFaultFault;
    }

    public PlatformConfigFaultFaultMsg(String message, vmware.vim25.PlatformConfigFault platformConfigFaultFault, Throwable cause) {
        super(message, cause);
        this.platformConfigFaultFault = platformConfigFaultFault;
    }

    public vmware.vim25.PlatformConfigFault getFaultInfo() {
        return this.platformConfigFaultFault;
    }
}
