
package vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-17T16:08:07.873+02:00
 * Generated source version: 2.7.5
 */

@WebFault(name = "ProfileUpdateFailedFault", targetNamespace = "urn:vim25")
public class ProfileUpdateFailedFaultMsg extends Exception {
    
    private vmware.vim25.ProfileUpdateFailed profileUpdateFailedFault;

    public ProfileUpdateFailedFaultMsg() {
        super();
    }
    
    public ProfileUpdateFailedFaultMsg(String message) {
        super(message);
    }
    
    public ProfileUpdateFailedFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public ProfileUpdateFailedFaultMsg(String message, vmware.vim25.ProfileUpdateFailed profileUpdateFailedFault) {
        super(message);
        this.profileUpdateFailedFault = profileUpdateFailedFault;
    }

    public ProfileUpdateFailedFaultMsg(String message, vmware.vim25.ProfileUpdateFailed profileUpdateFailedFault, Throwable cause) {
        super(message, cause);
        this.profileUpdateFailedFault = profileUpdateFailedFault;
    }

    public vmware.vim25.ProfileUpdateFailed getFaultInfo() {
        return this.profileUpdateFailedFault;
    }
}
