
package vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-17T16:08:07.859+02:00
 * Generated source version: 2.7.5
 */

@WebFault(name = "RecordReplayDisabledFault", targetNamespace = "urn:vim25")
public class RecordReplayDisabledFaultMsg extends Exception {
    
    private vmware.vim25.RecordReplayDisabled recordReplayDisabledFault;

    public RecordReplayDisabledFaultMsg() {
        super();
    }
    
    public RecordReplayDisabledFaultMsg(String message) {
        super(message);
    }
    
    public RecordReplayDisabledFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public RecordReplayDisabledFaultMsg(String message, vmware.vim25.RecordReplayDisabled recordReplayDisabledFault) {
        super(message);
        this.recordReplayDisabledFault = recordReplayDisabledFault;
    }

    public RecordReplayDisabledFaultMsg(String message, vmware.vim25.RecordReplayDisabled recordReplayDisabledFault, Throwable cause) {
        super(message, cause);
        this.recordReplayDisabledFault = recordReplayDisabledFault;
    }

    public vmware.vim25.RecordReplayDisabled getFaultInfo() {
        return this.recordReplayDisabledFault;
    }
}
