
package vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-17T16:08:07.862+02:00
 * Generated source version: 2.7.5
 */

@WebFault(name = "RemoveFailedFault", targetNamespace = "urn:vim25")
public class RemoveFailedFaultMsg extends Exception {
    
    private vmware.vim25.RemoveFailed removeFailedFault;

    public RemoveFailedFaultMsg() {
        super();
    }
    
    public RemoveFailedFaultMsg(String message) {
        super(message);
    }
    
    public RemoveFailedFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public RemoveFailedFaultMsg(String message, vmware.vim25.RemoveFailed removeFailedFault) {
        super(message);
        this.removeFailedFault = removeFailedFault;
    }

    public RemoveFailedFaultMsg(String message, vmware.vim25.RemoveFailed removeFailedFault, Throwable cause) {
        super(message, cause);
        this.removeFailedFault = removeFailedFault;
    }

    public vmware.vim25.RemoveFailed getFaultInfo() {
        return this.removeFailedFault;
    }
}
