
package vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-17T16:08:07.359+02:00
 * Generated source version: 2.7.5
 */

@WebFault(name = "RequestCanceledFault", targetNamespace = "urn:vim25")
public class RequestCanceledFaultMsg extends Exception {
    
    private vmware.vim25.RequestCanceled requestCanceledFault;

    public RequestCanceledFaultMsg() {
        super();
    }
    
    public RequestCanceledFaultMsg(String message) {
        super(message);
    }
    
    public RequestCanceledFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public RequestCanceledFaultMsg(String message, vmware.vim25.RequestCanceled requestCanceledFault) {
        super(message);
        this.requestCanceledFault = requestCanceledFault;
    }

    public RequestCanceledFaultMsg(String message, vmware.vim25.RequestCanceled requestCanceledFault, Throwable cause) {
        super(message, cause);
        this.requestCanceledFault = requestCanceledFault;
    }

    public vmware.vim25.RequestCanceled getFaultInfo() {
        return this.requestCanceledFault;
    }
}
