
package vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-17T16:08:07.381+02:00
 * Generated source version: 2.7.5
 */

@WebFault(name = "ResourceInUseFault", targetNamespace = "urn:vim25")
public class ResourceInUseFaultMsg extends Exception {
    
    private vmware.vim25.ResourceInUse resourceInUseFault;

    public ResourceInUseFaultMsg() {
        super();
    }
    
    public ResourceInUseFaultMsg(String message) {
        super(message);
    }
    
    public ResourceInUseFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public ResourceInUseFaultMsg(String message, vmware.vim25.ResourceInUse resourceInUseFault) {
        super(message);
        this.resourceInUseFault = resourceInUseFault;
    }

    public ResourceInUseFaultMsg(String message, vmware.vim25.ResourceInUse resourceInUseFault, Throwable cause) {
        super(message, cause);
        this.resourceInUseFault = resourceInUseFault;
    }

    public vmware.vim25.ResourceInUse getFaultInfo() {
        return this.resourceInUseFault;
    }
}
