
package vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-17T16:08:06.963+02:00
 * Generated source version: 2.7.5
 */

@WebFault(name = "RuntimeFaultFault", targetNamespace = "urn:vim25")
public class RuntimeFaultFaultMsg extends Exception {
    
    private vmware.vim25.RuntimeFault runtimeFaultFault;

    public RuntimeFaultFaultMsg() {
        super();
    }
    
    public RuntimeFaultFaultMsg(String message) {
        super(message);
    }
    
    public RuntimeFaultFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public RuntimeFaultFaultMsg(String message, vmware.vim25.RuntimeFault runtimeFaultFault) {
        super(message);
        this.runtimeFaultFault = runtimeFaultFault;
    }

    public RuntimeFaultFaultMsg(String message, vmware.vim25.RuntimeFault runtimeFaultFault, Throwable cause) {
        super(message, cause);
        this.runtimeFaultFault = runtimeFaultFault;
    }

    public vmware.vim25.RuntimeFault getFaultInfo() {
        return this.runtimeFaultFault;
    }
}
