
package vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-17T16:08:07.455+02:00
 * Generated source version: 2.7.5
 */

@WebFault(name = "SnapshotFaultFault", targetNamespace = "urn:vim25")
public class SnapshotFaultFaultMsg extends Exception {
    
    private vmware.vim25.SnapshotFault snapshotFaultFault;

    public SnapshotFaultFaultMsg() {
        super();
    }
    
    public SnapshotFaultFaultMsg(String message) {
        super(message);
    }
    
    public SnapshotFaultFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public SnapshotFaultFaultMsg(String message, vmware.vim25.SnapshotFault snapshotFaultFault) {
        super(message);
        this.snapshotFaultFault = snapshotFaultFault;
    }

    public SnapshotFaultFaultMsg(String message, vmware.vim25.SnapshotFault snapshotFaultFault, Throwable cause) {
        super(message, cause);
        this.snapshotFaultFault = snapshotFaultFault;
    }

    public vmware.vim25.SnapshotFault getFaultInfo() {
        return this.snapshotFaultFault;
    }
}
