
package vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-17T16:08:07.445+02:00
 * Generated source version: 2.7.5
 */

@WebFault(name = "SSPIChallengeFault", targetNamespace = "urn:vim25")
public class SSPIChallengeFaultMsg extends Exception {
    
    private vmware.vim25.SSPIChallenge sspiChallengeFault;

    public SSPIChallengeFaultMsg() {
        super();
    }
    
    public SSPIChallengeFaultMsg(String message) {
        super(message);
    }
    
    public SSPIChallengeFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public SSPIChallengeFaultMsg(String message, vmware.vim25.SSPIChallenge sspiChallengeFault) {
        super(message);
        this.sspiChallengeFault = sspiChallengeFault;
    }

    public SSPIChallengeFaultMsg(String message, vmware.vim25.SSPIChallenge sspiChallengeFault, Throwable cause) {
        super(message, cause);
        this.sspiChallengeFault = sspiChallengeFault;
    }

    public vmware.vim25.SSPIChallenge getFaultInfo() {
        return this.sspiChallengeFault;
    }
}
