
package vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-17T16:08:07.251+02:00
 * Generated source version: 2.7.5
 */

@WebFault(name = "TaskInProgressFault", targetNamespace = "urn:vim25")
public class TaskInProgressFaultMsg extends Exception {
    
    private vmware.vim25.TaskInProgress taskInProgressFault;

    public TaskInProgressFaultMsg() {
        super();
    }
    
    public TaskInProgressFaultMsg(String message) {
        super(message);
    }
    
    public TaskInProgressFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public TaskInProgressFaultMsg(String message, vmware.vim25.TaskInProgress taskInProgressFault) {
        super(message);
        this.taskInProgressFault = taskInProgressFault;
    }

    public TaskInProgressFaultMsg(String message, vmware.vim25.TaskInProgress taskInProgressFault, Throwable cause) {
        super(message, cause);
        this.taskInProgressFault = taskInProgressFault;
    }

    public vmware.vim25.TaskInProgress getFaultInfo() {
        return this.taskInProgressFault;
    }
}
