
package vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-17T16:08:07.474+02:00
 * Generated source version: 2.7.5
 */

@WebFault(name = "TimedoutFault", targetNamespace = "urn:vim25")
public class TimedoutFaultMsg extends Exception {
    
    private vmware.vim25.Timedout timedoutFault;

    public TimedoutFaultMsg() {
        super();
    }
    
    public TimedoutFaultMsg(String message) {
        super(message);
    }
    
    public TimedoutFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public TimedoutFaultMsg(String message, vmware.vim25.Timedout timedoutFault) {
        super(message);
        this.timedoutFault = timedoutFault;
    }

    public TimedoutFaultMsg(String message, vmware.vim25.Timedout timedoutFault, Throwable cause) {
        super(message, cause);
        this.timedoutFault = timedoutFault;
    }

    public vmware.vim25.Timedout getFaultInfo() {
        return this.timedoutFault;
    }
}
