
package vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-17T16:08:07.459+02:00
 * Generated source version: 2.7.5
 */

@WebFault(name = "ToolsUnavailableFault", targetNamespace = "urn:vim25")
public class ToolsUnavailableFaultMsg extends Exception {
    
    private vmware.vim25.ToolsUnavailable toolsUnavailableFault;

    public ToolsUnavailableFaultMsg() {
        super();
    }
    
    public ToolsUnavailableFaultMsg(String message) {
        super(message);
    }
    
    public ToolsUnavailableFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public ToolsUnavailableFaultMsg(String message, vmware.vim25.ToolsUnavailable toolsUnavailableFault) {
        super(message);
        this.toolsUnavailableFault = toolsUnavailableFault;
    }

    public ToolsUnavailableFaultMsg(String message, vmware.vim25.ToolsUnavailable toolsUnavailableFault, Throwable cause) {
        super(message, cause);
        this.toolsUnavailableFault = toolsUnavailableFault;
    }

    public vmware.vim25.ToolsUnavailable getFaultInfo() {
        return this.toolsUnavailableFault;
    }
}
