
package vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-17T16:08:07.221+02:00
 * Generated source version: 2.7.5
 */

@WebFault(name = "TooManyHostsFault", targetNamespace = "urn:vim25")
public class TooManyHostsFaultMsg extends Exception {
    
    private vmware.vim25.TooManyHosts tooManyHostsFault;

    public TooManyHostsFaultMsg() {
        super();
    }
    
    public TooManyHostsFaultMsg(String message) {
        super(message);
    }
    
    public TooManyHostsFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public TooManyHostsFaultMsg(String message, vmware.vim25.TooManyHosts tooManyHostsFault) {
        super(message);
        this.tooManyHostsFault = tooManyHostsFault;
    }

    public TooManyHostsFaultMsg(String message, vmware.vim25.TooManyHosts tooManyHostsFault, Throwable cause) {
        super(message, cause);
        this.tooManyHostsFault = tooManyHostsFault;
    }

    public vmware.vim25.TooManyHosts getFaultInfo() {
        return this.tooManyHostsFault;
    }
}
