
package vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-17T16:08:07.424+02:00
 * Generated source version: 2.7.5
 */

@WebFault(name = "UserNotFoundFault", targetNamespace = "urn:vim25")
public class UserNotFoundFaultMsg extends Exception {
    
    private vmware.vim25.UserNotFound userNotFoundFault;

    public UserNotFoundFaultMsg() {
        super();
    }
    
    public UserNotFoundFaultMsg(String message) {
        super(message);
    }
    
    public UserNotFoundFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public UserNotFoundFaultMsg(String message, vmware.vim25.UserNotFound userNotFoundFault) {
        super(message);
        this.userNotFoundFault = userNotFoundFault;
    }

    public UserNotFoundFaultMsg(String message, vmware.vim25.UserNotFound userNotFoundFault, Throwable cause) {
        super(message, cause);
        this.userNotFoundFault = userNotFoundFault;
    }

    public vmware.vim25.UserNotFound getFaultInfo() {
        return this.userNotFoundFault;
    }
}
