
package vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-17T16:08:07.419+02:00
 * Generated source version: 2.7.5
 */

@WebFault(name = "VAppConfigFaultFault", targetNamespace = "urn:vim25")
public class VAppConfigFaultFaultMsg extends Exception {
    
    private vmware.vim25.VAppConfigFault vAppConfigFaultFault;

    public VAppConfigFaultFaultMsg() {
        super();
    }
    
    public VAppConfigFaultFaultMsg(String message) {
        super(message);
    }
    
    public VAppConfigFaultFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public VAppConfigFaultFaultMsg(String message, vmware.vim25.VAppConfigFault vAppConfigFaultFault) {
        super(message);
        this.vAppConfigFaultFault = vAppConfigFaultFault;
    }

    public VAppConfigFaultFaultMsg(String message, vmware.vim25.VAppConfigFault vAppConfigFaultFault, Throwable cause) {
        super(message, cause);
        this.vAppConfigFaultFault = vAppConfigFaultFault;
    }

    public vmware.vim25.VAppConfigFault getFaultInfo() {
        return this.vAppConfigFaultFault;
    }
}
