
package vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-17T16:08:07.429+02:00
 * Generated source version: 2.7.5
 */

@WebFault(name = "VmFaultToleranceIssueFault", targetNamespace = "urn:vim25")
public class VmFaultToleranceIssueFaultMsg extends Exception {
    
    private vmware.vim25.VmFaultToleranceIssue vmFaultToleranceIssueFault;

    public VmFaultToleranceIssueFaultMsg() {
        super();
    }
    
    public VmFaultToleranceIssueFaultMsg(String message) {
        super(message);
    }
    
    public VmFaultToleranceIssueFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public VmFaultToleranceIssueFaultMsg(String message, vmware.vim25.VmFaultToleranceIssue vmFaultToleranceIssueFault) {
        super(message);
        this.vmFaultToleranceIssueFault = vmFaultToleranceIssueFault;
    }

    public VmFaultToleranceIssueFaultMsg(String message, vmware.vim25.VmFaultToleranceIssue vmFaultToleranceIssueFault, Throwable cause) {
        super(message, cause);
        this.vmFaultToleranceIssueFault = vmFaultToleranceIssueFault;
    }

    public vmware.vim25.VmFaultToleranceIssue getFaultInfo() {
        return this.vmFaultToleranceIssueFault;
    }
}
