
package vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-17T16:08:07.881+02:00
 * Generated source version: 2.7.5
 */

@WebFault(name = "VmfsAmbiguousMountFault", targetNamespace = "urn:vim25")
public class VmfsAmbiguousMountFaultMsg extends Exception {
    
    private vmware.vim25.VmfsAmbiguousMount vmfsAmbiguousMountFault;

    public VmfsAmbiguousMountFaultMsg() {
        super();
    }
    
    public VmfsAmbiguousMountFaultMsg(String message) {
        super(message);
    }
    
    public VmfsAmbiguousMountFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public VmfsAmbiguousMountFaultMsg(String message, vmware.vim25.VmfsAmbiguousMount vmfsAmbiguousMountFault) {
        super(message);
        this.vmfsAmbiguousMountFault = vmfsAmbiguousMountFault;
    }

    public VmfsAmbiguousMountFaultMsg(String message, vmware.vim25.VmfsAmbiguousMount vmfsAmbiguousMountFault, Throwable cause) {
        super(message, cause);
        this.vmfsAmbiguousMountFault = vmfsAmbiguousMountFault;
    }

    public vmware.vim25.VmfsAmbiguousMount getFaultInfo() {
        return this.vmfsAmbiguousMountFault;
    }
}
