
package vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-06-17T16:08:07.767+02:00
 * Generated source version: 2.7.5
 */

@WebFault(name = "VmToolsUpgradeFaultFault", targetNamespace = "urn:vim25")
public class VmToolsUpgradeFaultFaultMsg extends Exception {
    
    private vmware.vim25.VmToolsUpgradeFault vmToolsUpgradeFaultFault;

    public VmToolsUpgradeFaultFaultMsg() {
        super();
    }
    
    public VmToolsUpgradeFaultFaultMsg(String message) {
        super(message);
    }
    
    public VmToolsUpgradeFaultFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public VmToolsUpgradeFaultFaultMsg(String message, vmware.vim25.VmToolsUpgradeFault vmToolsUpgradeFaultFault) {
        super(message);
        this.vmToolsUpgradeFaultFault = vmToolsUpgradeFaultFault;
    }

    public VmToolsUpgradeFaultFaultMsg(String message, vmware.vim25.VmToolsUpgradeFault vmToolsUpgradeFaultFault, Throwable cause) {
        super(message, cause);
        this.vmToolsUpgradeFaultFault = vmToolsUpgradeFaultFault;
    }

    public vmware.vim25.VmToolsUpgradeFault getFaultInfo() {
        return this.vmToolsUpgradeFaultFault;
    }
}
